language: node_js
node_js:
- '0.10'
before_install: npm install -g mocha
deploy:
  provider: s3
  access_key_id: AKIAJRWXVR2NWJKFN4EA
  secret_access_key:
    secure: YgxrIc1X2Kw5aN84cALMru4CL+OsRhO6sQ9JemeW/L4vSFY6qKWwRxdeV5JXRXgcsWyKX7SeLXqlfnR+oIWP2ejG6VBBXFxDJCqp0gz0ZUsYcGwTHk0dwGfq4jjZIt1gbYTeuxznrTc3tA/JHnsDftiaPM1vpvp1SOmtSnMN1AM=
  bucket: kkpbucketsource
  upload-dir: web
  on:
    repo: kk90/AWSproject
